// Code generated by sbt-mavgen. Manual edits will be overwritten
package scavlink.message.matrixpilot

import scavlink.message._
import scavlink.message.enums.MavCmd

import scavlink.message.common.CommandLong
import scavlink.coord.Coordinates
import scavlink.coord.Geo

/**
 * Request storage of different parameter values and logs. This command will be only accepted if in pre-flight mode.
 * @param storageAction Storage action: Action defined by MAV_PREFLIGHT_STORAGE_ACTION_ADVANCED
 * @param storageArea Storage area as defined by parameter database
 * @param storageFlags Storage flags as defined by parameter database
 */
case class PreflightStorageAdvanced(targetSystem: SystemId = 0, targetComponent: ComponentId = 0, storageAction: Float = 0, storageArea: Float = 0, storageFlags: Float = 0)
extends Command {
  val cmd = MavCmd(0)
  val message = CommandLong(targetSystem, targetComponent, cmd, param1 = storageAction, param2 = storageArea, param3 = storageFlags)
  override def toString = cmd.toString + " storageAction=" + storageAction + " storageArea=" + storageArea + " storageFlags=" + storageFlags 
}
