// Code generated by sbt-mavgen. Manual edits will be overwritten
package scavlink.message.ualberta

import scavlink.message._
import scavlink.message.enums.MavCmd

import scavlink.message.common.CommandLong
import scavlink.coord.Coordinates
import scavlink.coord.Geo
