// Code generated by sbt-mavgen. Manual edits will be overwritten
package scavlink.message.autoquad

import scavlink.message._
import scavlink.message.enums._

/**
 * Sends up to 20 raw float values.
 * @param index Index of message
 * @param value1 value1
 * @param value2 value2
 * @param value3 value3
 * @param value4 value4
 * @param value5 value5
 * @param value6 value6
 * @param value7 value7
 * @param value8 value8
 * @param value9 value9
 * @param value10 value10
 * @param value11 value11
 * @param value12 value12
 * @param value13 value13
 * @param value14 value14
 * @param value15 value15
 * @param value16 value16
 * @param value17 value17
 * @param value18 value18
 * @param value19 value19
 * @param value20 value20
 */
case class AqTelemetryF(index: Short = 0, value1: Float = 0, value2: Float = 0, value3: Float = 0, value4: Float = 0, value5: Float = 0, value6: Float = 0, value7: Float = 0, value8: Float = 0, value9: Float = 0, value10: Float = 0, value11: Float = 0, value12: Float = 0, value13: Float = 0, value14: Float = 0, value15: Float = 0, value16: Float = 0, value17: Float = 0, value18: Float = 0, value19: Float = 0, value20: Float = 0)
extends Message {
  val _id = 150
  val _name = "AQ_TELEMETRY_F"
  val _bundle = Bundle.autoquad
  override def toString = "AQ_TELEMETRY_F" + " index=" + index + " value1=" + value1 + " value2=" + value2 + " value3=" + value3 + " value4=" + value4 + " value5=" + value5 + " value6=" + value6 + " value7=" + value7 + " value8=" + value8 + " value9=" + value9 + " value10=" + value10 + " value11=" + value11 + " value12=" + value12 + " value13=" + value13 + " value14=" + value14 + " value15=" + value15 + " value16=" + value16 + " value17=" + value17 + " value18=" + value18 + " value19=" + value19 + " value20=" + value20
}
