// Code generated by sbt-mavgen. Manual edits will be overwritten
package scavlink.message.pixhawk

import scavlink.message._
import scavlink.message.enums.MavCmd

import scavlink.message.common.CommandLong
import scavlink.coord.Coordinates
import scavlink.coord.Geo

/**
 * Starts a search
 * @param param1 1 to arm, 0 to disarm
 */
case class DoStartSearch(targetSystem: SystemId = 0, targetComponent: ComponentId = 0, param1: Float = 0)
extends Command {
  val cmd = MavCmd(10001)
  val message = CommandLong(targetSystem, targetComponent, cmd, param1 = param1)
  override def toString = cmd.toString + " param1=" + param1 
}

/**
 * Starts a search
 * @param param1 1 to arm, 0 to disarm
 */
case class DoFinishSearch(targetSystem: SystemId = 0, targetComponent: ComponentId = 0, param1: Float = 0)
extends Command {
  val cmd = MavCmd(10002)
  val message = CommandLong(targetSystem, targetComponent, cmd, param1 = param1)
  override def toString = cmd.toString + " param1=" + param1 
}

/**
 * Starts a search
 * @param param1 1 to arm, 0 to disarm
 */
case class NavSweep(targetSystem: SystemId = 0, targetComponent: ComponentId = 0, param1: Float = 0)
extends Command {
  val cmd = MavCmd(10003)
  val message = CommandLong(targetSystem, targetComponent, cmd, param1 = param1)
  override def toString = cmd.toString + " param1=" + param1 
}
