// Code generated by sbt-mavgen. Manual edits will be overwritten
package scavlink.message

import scavlink.connection.marshal._

case class Bundle(name: String, marshaller: MessageMarshaller)

object Bundle {
  val common = Bundle("common", CommonMarshaller)
  val ASLUAV = Bundle("ASLUAV", ASLUAVMarshaller)
  val ardupilotmega = Bundle("ardupilotmega", ArdupilotmegaMarshaller)
  val autoquad = Bundle("autoquad", AutoquadMarshaller)
  val matrixpilot = Bundle("matrixpilot", MatrixpilotMarshaller)
  val pixhawk = Bundle("pixhawk", PixhawkMarshaller)
  val sensesoar = Bundle("sensesoar", SensesoarMarshaller)
  val slugs = Bundle("slugs", SlugsMarshaller)
  val ualberta = Bundle("ualberta", UalbertaMarshaller)
}
