// Code generated by sbt-mavgen. Manual edits will be overwritten
package scavlink.message.enums

/**
 * Available operating modes/statuses for AutoQuad flight controller. 
				Bitmask up to 32 bits. Low side bits for base modes, high side for 
				additional active features/modifiers/constraints.
 */
object AutoquadNavStatus extends Enumeration {
  /**
   * System is initializing
   */
  val INIT = Value(0)
  /**
   * System is standing by, not active
   */
  val STANDBY = Value(0x1)
  /**
   * Stabilized, under full manual control
   */
  val MANUAL = Value(0x2)
  /**
   * Altitude hold engaged
   */
  val ALTHOLD = Value(0x4)
  /**
   * Position hold engaged
   */
  val POSHOLD = Value(0x8)
  /**
   * Dynamic Velocity Hold is active
   */
  val DVH = Value(0x10)
  /**
   * Autonomous mission execution mode
   */
  val MISSION = Value(0x20)
  /**
   * System is in failsafe recovery mode
   */
  val FAILSAFE = Value(0x80000000)
  /**
   * Automatic Return to Home is active
   */
  val RTH = Value(0x40000000)
  /**
   * Heading-Free locked mode active
   */
  val HF_LOCKED = Value(0x20000000)
  /**
   * Heading-Free dynamic mode active
   */
  val HF_DYNAMIC = Value(0x10000000)
  /**
   * Ceiling altitude is set
   */
  val CEILING = Value(0x8000000)
  /**
   * Craft is at ceiling altitude
   */
  val CEILING_REACHED = Value(0x4000000)
}
