// Code generated by sbt-mavgen. Manual edits will be overwritten
package scavlink.message.enums

/**
 * These flags encode the control surfaces for selective passthrough mode. If a bit is set then the pilot console
            has control of the surface, and if not then the autopilot has control of the surface.
 */
object ControlSurfaceFlag extends Enumeration with Flag {
  val _UNKNOWN = Value(0)
  /**
   * 0b10000000 Throttle control passes through to pilot console.
   */
  val THROTTLE = Value(128)
  /**
   * 0b01000000 Left aileron control passes through to pilot console.
   */
  val LEFT_AILERON = Value(64)
  /**
   * 0b00100000 Right aileron control passes through to pilot console.
   */
  val RIGHT_AILERON = Value(32)
  /**
   * 0b00010000 Rudder control passes through to pilot console.
   */
  val RUDDER = Value(16)
  /**
   * 0b00001000 Left elevator control passes through to pilot console.
   */
  val LEFT_ELEVATOR = Value(8)
  /**
   * 0b00000100 Right elevator control passes through to pilot console.
   */
  val RIGHT_ELEVATOR = Value(4)
  /**
   * 0b00000010 Left flap control passes through to pilot console.
   */
  val LEFT_FLAP = Value(2)
  /**
   * 0b00000001 Right flap control passes through to pilot console.
   */
  val RIGHT_FLAP = Value(1)
}
