// Code generated by sbt-mavgen. Manual edits will be overwritten
package scavlink.message.enums

/**
 * Content Types for data transmission handshake
 */
object DataTypes extends Enumeration {
  val _UNKNOWN = Value(0)
  val JPEG_IMAGE = Value(1)
  val RAW_IMAGE = Value(2)
  val KINECT = Value(3)
}
