// Code generated by sbt-mavgen. Manual edits will be overwritten
package scavlink.message.enums

object FenceAction extends Enumeration {
  /**
   * Disable fenced mode
   */
  val NONE = Value(0)
  /**
   * Switched to guided mode to return point (fence point 0)
   */
  val GUIDED = Value(1)
  /**
   * Report fence breach, but don't take action
   */
  val REPORT = Value(2)
  /**
   * Switched to guided mode to return point (fence point 0) with manual throttle control
   */
  val GUIDED_THR_PASS = Value(3)
}
