// Code generated by sbt-mavgen. Manual edits will be overwritten
package scavlink.message.enums

/**
 * Gripper actions.
 */
object GripperActions extends Enumeration {
  /**
   * gripper release of cargo
   */
  val RELEASE = Value(0)
  /**
   * gripper grabs onto cargo
   */
  val GRAB = Value(1)
}
