// Code generated by sbt-mavgen. Manual edits will be overwritten
package scavlink.message.enums

object LimitsState extends Enumeration {
  /**
   * pre-initialization
   */
  val INIT = Value(0)
  /**
   * disabled
   */
  val DISABLED = Value(1)
  /**
   * checking limits
   */
  val ENABLED = Value(2)
  /**
   * a limit has been breached
   */
  val TRIGGERED = Value(3)
  /**
   * taking action eg. RTL
   */
  val RECOVERING = Value(4)
  /**
   * we're no longer in breach of a limit
   */
  val RECOVERED = Value(5)
}
