// Code generated by sbt-mavgen. Manual edits will be overwritten
package scavlink.message.enums

object LimitModule extends Enumeration with Flag {
  val _UNKNOWN = Value(0)
  /**
   * pre-initialization
   */
  val GPSLOCK = Value(1)
  /**
   * disabled
   */
  val GEOFENCE = Value(2)
  /**
   * checking limits
   */
  val ALTITUDE = Value(4)
}
