// Code generated by sbt-mavgen. Manual edits will be overwritten
package scavlink.message.enums

/**
 * Micro air vehicle / autopilot classes. This identifies the individual model.
 */
object MavAutopilot extends Enumeration {
  /**
   * Generic autopilot, full support for everything
   */
  val GENERIC = Value(0)
  /**
   * PIXHAWK autopilot, http://pixhawk.ethz.ch
   */
  val PIXHAWK = Value(1)
  /**
   * SLUGS autopilot, http://slugsuav.soe.ucsc.edu
   */
  val SLUGS = Value(2)
  /**
   * ArduPilotMega / ArduCopter, http://diydrones.com
   */
  val ARDUPILOTMEGA = Value(3)
  /**
   * OpenPilot, http://openpilot.org
   */
  val OPENPILOT = Value(4)
  /**
   * Generic autopilot only supporting simple waypoints
   */
  val GENERIC_WAYPOINTS_ONLY = Value(5)
  /**
   * Generic autopilot supporting waypoints and other simple navigation commands
   */
  val GENERIC_WAYPOINTS_AND_SIMPLE_NAVIGATION_ONLY = Value(6)
  /**
   * Generic autopilot supporting the full mission command set
   */
  val GENERIC_MISSION_FULL = Value(7)
  /**
   * No valid autopilot, e.g. a GCS or other MAVLink component
   */
  val INVALID = Value(8)
  /**
   * PPZ UAV - http://nongnu.org/paparazzi
   */
  val PPZ = Value(9)
  /**
   * UAV Dev Board
   */
  val UDB = Value(10)
  /**
   * FlexiPilot
   */
  val FP = Value(11)
  /**
   * PX4 Autopilot - http://pixhawk.ethz.ch/px4/
   */
  val PX4 = Value(12)
  /**
   * SMACCMPilot - http://smaccmpilot.org
   */
  val SMACCMPILOT = Value(13)
  /**
   * AutoQuad -- http://autoquad.org
   */
  val AUTOQUAD = Value(14)
  /**
   * Armazila -- http://armazila.com
   */
  val ARMAZILA = Value(15)
  /**
   * Aerob -- http://aerob.ru
   */
  val AEROB = Value(16)
  /**
   * ASLUAV autopilot -- http://www.asl.ethz.ch
   */
  val ASLUAV = Value(17)
}
