// Code generated by sbt-mavgen. Manual edits will be overwritten
package scavlink.message.enums

/**
 * Enumeration of battery functions
 */
object MavBatteryFunction extends Enumeration {
  /**
   * Lithium polymere battery
   */
  val UNKNOWN = Value(0)
  /**
   * Battery supports all flight systems
   */
  val ALL = Value(1)
  /**
   * Battery for the propulsion system
   */
  val PROPULSION = Value(2)
  /**
   * Avionics battery
   */
  val AVIONICS = Value(3)
  /**
   * Payload battery
   */
  val TYPE_PAYLOAD = Value(4)
}
