// Code generated by sbt-mavgen. Manual edits will be overwritten
package scavlink.message.enums

/**
 * Enumeration of battery types
 */
object MavBatteryType extends Enumeration {
  /**
   * Not specified.
   */
  val UNKNOWN = Value(0)
  /**
   * Lithium polymere battery
   */
  val LIPO = Value(1)
  /**
   * Lithium ferrite battery
   */
  val LIFE = Value(2)
  /**
   * Lithium-ION battery
   */
  val LION = Value(3)
  /**
   * Nickel metal hydride battery
   */
  val NIMH = Value(4)
}
