// Code generated by sbt-mavgen. Manual edits will be overwritten
package scavlink.message.enums

/**
 * ACK / NACK / ERROR values as a result of MAV_CMDs and for mission item transmission.
 */
object MavCmdAck extends Enumeration {
  val _UNKNOWN = Value(0)
  /**
   * Command / mission item is ok.
   */
  val OK = Value(1)
  /**
   * Generic error message if none of the other reasons fails or if no detailed error reporting is implemented.
   */
  val ERR_FAIL = Value(2)
  /**
   * The system is refusing to accept this command from this source / communication partner.
   */
  val ERR_ACCESS_DENIED = Value(3)
  /**
   * Command or mission item is not supported, other commands would be accepted.
   */
  val ERR_NOT_SUPPORTED = Value(4)
  /**
   * The coordinate frame of this command / mission item is not supported.
   */
  val ERR_COORDINATE_FRAME_NOT_SUPPORTED = Value(5)
  /**
   * The coordinate frame of this command is ok, but he coordinate values exceed the safety limits of this system. This is a generic error, please use the more specific error messages below if possible.
   */
  val ERR_COORDINATES_OUT_OF_RANGE = Value(6)
  /**
   * The X or latitude value is out of range.
   */
  val ERR_X_LAT_OUT_OF_RANGE = Value(7)
  /**
   * The Y or longitude value is out of range.
   */
  val ERR_Y_LON_OUT_OF_RANGE = Value(8)
  /**
   * The Z or altitude value is out of range.
   */
  val ERR_Z_ALT_OUT_OF_RANGE = Value(9)
}
