// Code generated by sbt-mavgen. Manual edits will be overwritten
package scavlink.message.enums

/**
 * Data stream IDs. A data stream is not a fixed set of messages, but rather a
     recommendation to the autopilot software. Individual autopilots may or may not obey
     the recommended messages.
 */
object MavDataStream extends Enumeration {
  /**
   * Enable all data streams
   */
  val ALL = Value(0)
  /**
   * Enable IMU_RAW, GPS_RAW, GPS_STATUS packets.
   */
  val RAW_SENSORS = Value(1)
  /**
   * Enable GPS_STATUS, CONTROL_STATUS, AUX_STATUS
   */
  val EXTENDED_STATUS = Value(2)
  /**
   * Enable RC_CHANNELS_SCALED, RC_CHANNELS_RAW, SERVO_OUTPUT_RAW
   */
  val RC_CHANNELS = Value(3)
  /**
   * Enable ATTITUDE_CONTROLLER_OUTPUT, POSITION_CONTROLLER_OUTPUT, NAV_CONTROLLER_OUTPUT.
   */
  val RAW_CONTROLLER = Value(4)
  /**
   * Enable LOCAL_POSITION, GLOBAL_POSITION/GLOBAL_POSITION_INT messages.
   */
  val POSITION = Value(6)
  /**
   * Dependent on the autopilot
   */
  val EXTRA1 = Value(10)
  /**
   * Dependent on the autopilot
   */
  val EXTRA2 = Value(11)
  /**
   * Dependent on the autopilot
   */
  val EXTRA3 = Value(12)
}
