// Code generated by sbt-mavgen. Manual edits will be overwritten
package scavlink.message.enums

/**
 * Enumeration of estimator types
 */
object MavEstimatorType extends Enumeration {
  val _UNKNOWN = Value(0)
  /**
   * This is a naive estimator without any real covariance feedback.
   */
  val NAIVE = Value(1)
  /**
   * Computer vision based estimate. Might be up to scale.
   */
  val VISION = Value(2)
  /**
   * Visual-inertial estimate.
   */
  val VIO = Value(3)
  /**
   * Plain GPS estimate.
   */
  val GPS = Value(4)
  /**
   * Estimator integrating GPS and inertial sensing.
   */
  val GPS_INS = Value(5)
}
