// Code generated by sbt-mavgen. Manual edits will be overwritten
package scavlink.message.enums

/**
 * Override command, pauses current mission execution and moves immediately to a position
 */
object MavGoto extends Enumeration {
  /**
   * Hold at the current position.
   */
  val DO_HOLD = Value(0)
  /**
   * Continue with the next item in mission execution.
   */
  val DO_CONTINUE = Value(1)
  /**
   * Hold at the current position of the system
   */
  val HOLD_AT_CURRENT_POSITION = Value(2)
  /**
   * Hold at the position specified in the parameters of the DO_HOLD action
   */
  val HOLD_AT_SPECIFIED_POSITION = Value(3)
}
