// Code generated by sbt-mavgen. Manual edits will be overwritten
package scavlink.message.enums

object MavlinkDataStreamType extends Enumeration {
  val _UNKNOWN = Value(0)
  val JPEG = Value(1)
  val BMP = Value(2)
  val RAW8U = Value(3)
  val RAW32U = Value(4)
  val PGM = Value(5)
  val PNG = Value(6)
}
