// Code generated by sbt-mavgen. Manual edits will be overwritten
package scavlink.message.enums

/**
 * These defines are predefined OR-combined mode flags. There is no need to use values from this enum, but it
               simplifies the use of the mode flags. Note that manual input is enabled in all modes as a safety override.
 */
object MavMode extends Enumeration {
  /**
   * System is not ready to fly, booting, calibrating, etc. No flag is set.
   */
  val PREFLIGHT = Value(0)
  /**
   * System is allowed to be active, under assisted RC control.
   */
  val STABILIZE_DISARMED = Value(80)
  /**
   * System is allowed to be active, under assisted RC control.
   */
  val STABILIZE_ARMED = Value(208)
  /**
   * System is allowed to be active, under manual (RC) control, no stabilization
   */
  val MANUAL_DISARMED = Value(64)
  /**
   * System is allowed to be active, under manual (RC) control, no stabilization
   */
  val MANUAL_ARMED = Value(192)
  /**
   * System is allowed to be active, under autonomous control, manual setpoint
   */
  val GUIDED_DISARMED = Value(88)
  /**
   * System is allowed to be active, under autonomous control, manual setpoint
   */
  val GUIDED_ARMED = Value(216)
  /**
   * System is allowed to be active, under autonomous control and navigation (the trajectory is decided onboard and not pre-programmed by MISSIONs)
   */
  val AUTO_DISARMED = Value(92)
  /**
   * System is allowed to be active, under autonomous control and navigation (the trajectory is decided onboard and not pre-programmed by MISSIONs)
   */
  val AUTO_ARMED = Value(220)
  /**
   * UNDEFINED mode. This solely depends on the autopilot - use with caution, intended for developers only.
   */
  val TEST_DISARMED = Value(66)
  /**
   * UNDEFINED mode. This solely depends on the autopilot - use with caution, intended for developers only.
   */
  val TEST_ARMED = Value(194)
}
