// Code generated by sbt-mavgen. Manual edits will be overwritten
package scavlink.message.enums

/**
 * Enumeration of possible mount operation modes
 */
object MavMountMode extends Enumeration {
  /**
   * Load and keep safe position (Roll,Pitch,Yaw) from permant memory and stop stabilization
   */
  val RETRACT = Value(0)
  /**
   * Load and keep neutral position (Roll,Pitch,Yaw) from permanent memory.
   */
  val NEUTRAL = Value(1)
  /**
   * Load neutral position and start MAVLink Roll,Pitch,Yaw control with stabilization
   */
  val MAVLINK_TARGETING = Value(2)
  /**
   * Load neutral position and start RC Roll,Pitch,Yaw control with stabilization
   */
  val RC_TARGETING = Value(3)
  /**
   * Load neutral position and start to point to Lat,Lon,Alt
   */
  val GPS_POINT = Value(4)
}
