// Code generated by sbt-mavgen. Manual edits will be overwritten
package scavlink.message.enums

/**
 * These values encode the bit positions of the decode position. These values can be used to read the value of a flag bit by combining the base_mode variable with AND with the flag position value. The result will be either 0 or 1, depending on if the flag is set or not.
 */
object MavModeFlagDecodePosition extends Enumeration with Flag {
  val _UNKNOWN = Value(0)
  /**
   * First bit:  10000000
   */
  val SAFETY = Value(128)
  /**
   * Second bit: 01000000
   */
  val MANUAL = Value(64)
  /**
   * Third bit:  00100000
   */
  val HIL = Value(32)
  /**
   * Fourth bit: 00010000
   */
  val STABILIZE = Value(16)
  /**
   * Fifth bit:  00001000
   */
  val GUIDED = Value(8)
  /**
   * Sixt bit:   00000100
   */
  val AUTO = Value(4)
  /**
   * Seventh bit: 00000010
   */
  val TEST = Value(2)
  /**
   * Eighth bit: 00000001
   */
  val CUSTOM_MODE = Value(1)
}
