// Code generated by sbt-mavgen. Manual edits will be overwritten
package scavlink.message.enums

/**
 * result in a mavlink mission ack
 */
object MavMissionResult extends Enumeration {
  /**
   * mission accepted OK
   */
  val ACCEPTED = Value(0)
  /**
   * generic error / not accepting mission commands at all right now
   */
  val ERROR = Value(1)
  /**
   * coordinate frame is not supported
   */
  val UNSUPPORTED_FRAME = Value(2)
  /**
   * command is not supported
   */
  val UNSUPPORTED = Value(3)
  /**
   * mission item exceeds storage space
   */
  val NO_SPACE = Value(4)
  /**
   * one of the parameters has an invalid value
   */
  val INVALID = Value(5)
  /**
   * param1 has an invalid value
   */
  val INVALID_PARAM1 = Value(6)
  /**
   * param2 has an invalid value
   */
  val INVALID_PARAM2 = Value(7)
  /**
   * param3 has an invalid value
   */
  val INVALID_PARAM3 = Value(8)
  /**
   * param4 has an invalid value
   */
  val INVALID_PARAM4 = Value(9)
  /**
   * x/param5 has an invalid value
   */
  val INVALID_PARAM5_X = Value(10)
  /**
   * y/param6 has an invalid value
   */
  val INVALID_PARAM6_Y = Value(11)
  /**
   * param7 has an invalid value
   */
  val INVALID_PARAM7 = Value(12)
  /**
   * received waypoint out of sequence
   */
  val INVALID_SEQUENCE = Value(13)
  /**
   * not accepting any mission commands from this communication partner
   */
  val DENIED = Value(14)
}
