// Code generated by sbt-mavgen. Manual edits will be overwritten
package scavlink.message.enums

/**
 * These flags encode the MAV mode.
 */
object MavModeFlag extends Enumeration with Flag {
  val _UNKNOWN = Value(0)
  /**
   * 0b10000000 MAV safety set to armed. Motors are enabled / running / can start. Ready to fly.
   */
  val SAFETY_ARMED = Value(128)
  /**
   * 0b01000000 remote control input is enabled.
   */
  val MANUAL_INPUT_ENABLED = Value(64)
  /**
   * 0b00100000 hardware in the loop simulation. All motors / actuators are blocked, but internal software is full operational.
   */
  val HIL_ENABLED = Value(32)
  /**
   * 0b00010000 system stabilizes electronically its attitude (and optionally position). It needs however further control inputs to move around.
   */
  val STABILIZE_ENABLED = Value(16)
  /**
   * 0b00001000 guided mode enabled, system flies MISSIONs / mission items.
   */
  val GUIDED_ENABLED = Value(8)
  /**
   * 0b00000100 autonomous mode enabled, system finds its own goal positions. Guided flag can be set or not, depends on the actual implementation.
   */
  val AUTO_ENABLED = Value(4)
  /**
   * 0b00000010 system has a test mode enabled. This flag is intended for temporary system tests and should not be used for stable implementations.
   */
  val TEST_ENABLED = Value(2)
  /**
   * 0b00000001 Reserved for future use.
   */
  val CUSTOM_MODE_ENABLED = Value(1)
}
