// Code generated by sbt-mavgen. Manual edits will be overwritten
package scavlink.message.enums

/**
 * Specifies the datatype of a MAVLink parameter.
 */
object MavParamType extends Enumeration {
  val _UNKNOWN = Value(0)
  /**
   * 8-bit unsigned integer
   */
  val UINT8 = Value(1)
  /**
   * 8-bit signed integer
   */
  val INT8 = Value(2)
  /**
   * 16-bit unsigned integer
   */
  val UINT16 = Value(3)
  /**
   * 16-bit signed integer
   */
  val INT16 = Value(4)
  /**
   * 32-bit unsigned integer
   */
  val UINT32 = Value(5)
  /**
   * 32-bit signed integer
   */
  val INT32 = Value(6)
  /**
   * 64-bit unsigned integer
   */
  val UINT64 = Value(7)
  /**
   * 64-bit signed integer
   */
  val INT64 = Value(8)
  /**
   * 32-bit floating-point
   */
  val REAL32 = Value(9)
  /**
   * 64-bit floating-point
   */
  val REAL64 = Value(10)
}
