// Code generated by sbt-mavgen. Manual edits will be overwritten
package scavlink.message.enums

/**
 * Action required when performing CMD_PREFLIGHT_STORAGE
 */
object MavPreflightStorageAction extends Enumeration {
  /**
   * Read all parameters from storage
   */
  val READ_ALL = Value(0)
  /**
   * Write all parameters to storage
   */
  val WRITE_ALL = Value(1)
  /**
   * Clear all  parameters in storage
   */
  val CLEAR_ALL = Value(2)
  /**
   * Read specific parameters from storage
   */
  val READ_SPECIFIC = Value(3)
  /**
   * Write specific parameters to storage
   */
  val WRITE_SPECIFIC = Value(4)
  /**
   * Clear specific parameters in storage
   */
  val CLEAR_SPECIFIC = Value(5)
  /**
   * do nothing
   */
  val DO_NOTHING = Value(6)
}
