// Code generated by sbt-mavgen. Manual edits will be overwritten
package scavlink.message.enums

/**
 * Power supply status flags (bitmask)
 */
object MavPowerStatus extends Enumeration with Flag {
  val _UNKNOWN = Value(0)
  /**
   * main brick power supply valid
   */
  val BRICK_VALID = Value(1)
  /**
   * main servo power supply valid for FMU
   */
  val SERVO_VALID = Value(2)
  /**
   * USB power is connected
   */
  val USB_CONNECTED = Value(4)
  /**
   * peripheral supply is in over-current state
   */
  val PERIPH_OVERCURRENT = Value(8)
  /**
   * hi-power peripheral supply is in over-current state
   */
  val PERIPH_HIPOWER_OVERCURRENT = Value(16)
  /**
   * Power status has changed since boot
   */
  val CHANGED = Value(32)
}
