// Code generated by sbt-mavgen. Manual edits will be overwritten
package scavlink.message.enums

/**
 * Bitmask of (optional) autopilot capabilities (64 bit). If a bit is set, the autopilot supports this capability.
 */
object MavProtocolCapability extends Enumeration with Flag {
  val _UNKNOWN = Value(0)
  /**
   * Autopilot supports MISSION float message type.
   */
  val MISSION_FLOAT = Value(1)
  /**
   * Autopilot supports the new param float message type.
   */
  val PARAM_FLOAT = Value(2)
  /**
   * Autopilot supports MISSION_INT scaled integer message type.
   */
  val MISSION_INT = Value(4)
  /**
   * Autopilot supports COMMAND_INT scaled integer message type.
   */
  val COMMAND_INT = Value(8)
  /**
   * Autopilot supports the new param union message type.
   */
  val PARAM_UNION = Value(16)
  /**
   * Autopilot supports the new param union message type.
   */
  val FTP = Value(32)
  /**
   * Autopilot supports commanding attitude offboard.
   */
  val SET_ATTITUDE_TARGET = Value(64)
  /**
   * Autopilot supports commanding position and velocity targets in local NED frame.
   */
  val SET_POSITION_TARGET_LOCAL_NED = Value(128)
  /**
   * Autopilot supports commanding position and velocity targets in global scaled integers.
   */
  val SET_POSITION_TARGET_GLOBAL_INT = Value(256)
  /**
   * Autopilot supports terrain protocol / data handling.
   */
  val TERRAIN = Value(512)
}
