// Code generated by sbt-mavgen. Manual edits will be overwritten
package scavlink.message.enums

/**
 * result from a mavlink command
 */
object MavResult extends Enumeration {
  /**
   * Command ACCEPTED and EXECUTED
   */
  val ACCEPTED = Value(0)
  /**
   * Command TEMPORARY REJECTED/DENIED
   */
  val TEMPORARILY_REJECTED = Value(1)
  /**
   * Command PERMANENTLY DENIED
   */
  val DENIED = Value(2)
  /**
   * Command UNKNOWN/UNSUPPORTED
   */
  val UNSUPPORTED = Value(3)
  /**
   * Command executed, but failed
   */
  val FAILED = Value(4)
}
