// Code generated by sbt-mavgen. Manual edits will be overwritten
package scavlink.message.enums

/**
 * The ROI (region of interest) for the vehicle. This can be
                be used by the vehicle for camera/vehicle attitude alignment (see
                MAV_CMD_NAV_ROI).
 */
object MavRoi extends Enumeration {
  /**
   * No region of interest.
   */
  val NONE = Value(0)
  /**
   * Point toward next MISSION.
   */
  val WPNEXT = Value(1)
  /**
   * Point toward given MISSION.
   */
  val WPINDEX = Value(2)
  /**
   * Point toward fixed location.
   */
  val LOCATION = Value(3)
  /**
   * Point toward of given id.
   */
  val TARGET = Value(4)
}
