// Code generated by sbt-mavgen. Manual edits will be overwritten
package scavlink.message.enums

/**
 * Indicates the severity level, generally used for status messages to indicate their relative urgency. Based on RFC-5424 using expanded definitions at: http://www.kiwisyslog.com/kb/info:-syslog-message-levels/.
 */
object MavSeverity extends Enumeration {
  /**
   * System is unusable. This is a "panic" condition.
   */
  val EMERGENCY = Value(0)
  /**
   * Action should be taken immediately. Indicates error in non-critical systems.
   */
  val ALERT = Value(1)
  /**
   * Action must be taken immediately. Indicates failure in a primary system.
   */
  val CRITICAL = Value(2)
  /**
   * Indicates an error in secondary/redundant systems.
   */
  val ERROR = Value(3)
  /**
   * Indicates about a possible future error if this is not resolved within a given timeframe. Example would be a low battery warning.
   */
  val WARNING = Value(4)
  /**
   * An unusual event has occured, though not an error condition. This should be investigated for the root cause.
   */
  val NOTICE = Value(5)
  /**
   * Normal operational messages. Useful for logging. No action is required for these messages.
   */
  val INFO = Value(6)
  /**
   * Useful non-operational messages that can assist in debugging. These should not occur during normal operation.
   */
  val DEBUG = Value(7)
}
