// Code generated by sbt-mavgen. Manual edits will be overwritten
package scavlink.message.enums

object MavState extends Enumeration {
  /**
   * Uninitialized system, state is unknown.
   */
  val UNINIT = Value(0)
  /**
   * System is booting up.
   */
  val BOOT = Value(1)
  /**
   * System is calibrating and not flight-ready.
   */
  val CALIBRATING = Value(2)
  /**
   * System is grounded and on standby. It can be launched any time.
   */
  val STANDBY = Value(3)
  /**
   * System is active and might be already airborne. Motors are engaged.
   */
  val ACTIVE = Value(4)
  /**
   * System is in a non-normal flight mode. It can however still navigate.
   */
  val CRITICAL = Value(5)
  /**
   * System is in a non-normal flight mode. It lost control over parts or over the whole airframe. It is in mayday and going down.
   */
  val EMERGENCY = Value(6)
  /**
   * System just initialized its power-down sequence, will shut down now.
   */
  val POWEROFF = Value(7)
}
