// Code generated by sbt-mavgen. Manual edits will be overwritten
package scavlink.message.enums

object MavType extends Enumeration {
  /**
   * Generic micro air vehicle.
   */
  val GENERIC = Value(0)
  /**
   * Fixed wing aircraft.
   */
  val FIXED_WING = Value(1)
  /**
   * Quadrotor
   */
  val QUADROTOR = Value(2)
  /**
   * Coaxial helicopter
   */
  val COAXIAL = Value(3)
  /**
   * Normal helicopter with tail rotor.
   */
  val HELICOPTER = Value(4)
  /**
   * Ground installation
   */
  val ANTENNA_TRACKER = Value(5)
  /**
   * Operator control unit / ground control station
   */
  val GCS = Value(6)
  /**
   * Airship, controlled
   */
  val AIRSHIP = Value(7)
  /**
   * Free balloon, uncontrolled
   */
  val FREE_BALLOON = Value(8)
  /**
   * Rocket
   */
  val ROCKET = Value(9)
  /**
   * Ground rover
   */
  val GROUND_ROVER = Value(10)
  /**
   * Surface vessel, boat, ship
   */
  val SURFACE_BOAT = Value(11)
  /**
   * Submarine
   */
  val SUBMARINE = Value(12)
  /**
   * Hexarotor
   */
  val HEXAROTOR = Value(13)
  /**
   * Octorotor
   */
  val OCTOROTOR = Value(14)
  /**
   * Octorotor
   */
  val TRICOPTER = Value(15)
  /**
   * Flapping wing
   */
  val FLAPPING_WING = Value(16)
  /**
   * Flapping wing
   */
  val KITE = Value(17)
  /**
   * Onboard companion controller
   */
  val ONBOARD_CONTROLLER = Value(18)
  /**
   * Two-rotor VTOL using control surfaces in vertical operation in addition. Tailsitter.
   */
  val VTOL_DUOROTOR = Value(19)
  /**
   * Quad-rotor VTOL using a V-shaped quad config in vertical operation. Tailsitter.
   */
  val VTOL_QUADROTOR = Value(20)
}
