// Code generated by sbt-mavgen. Manual edits will be overwritten
package scavlink.message.enums

object MotorTestThrottleType extends Enumeration {
  /**
   * throttle as a percentage from 0 ~ 100
   */
  val PERCENT = Value(0)
  /**
   * throttle as an absolute PWM value (normally in range of 1000~2000)
   */
  val PWM = Value(1)
  /**
   * throttle pass-through from pilot's transmitter
   */
  val PILOT = Value(2)
}
