// Code generated by sbt-mavgen. Manual edits will be overwritten
package scavlink.message.enums

object ParachuteAction extends Enumeration {
  /**
   * Disable parachute release
   */
  val DISABLE = Value(0)
  /**
   * Enable parachute release
   */
  val ENABLE = Value(1)
  /**
   * Release parachute
   */
  val RELEASE = Value(2)
}
