// Code generated by sbt-mavgen. Manual edits will be overwritten
package scavlink.message.enums

/**
 * Flags in RALLY_POINT message
 */
object RallyFlags extends Enumeration with Flag {
  val _UNKNOWN = Value(0)
  /**
   * Flag set when requiring favorable winds for landing.
   */
  val FAVORABLE_WIND = Value(1)
  /**
   * Flag set when plane is to immediately descend to break altitude and land without GCS intervention.  Flag not set when plane is to loiter at Rally point until commanded to land.
   */
  val LAND_IMMEDIATELY = Value(2)
}
