// Code generated by sbt-mavgen. Manual edits will be overwritten
package scavlink.message.enums

/**
 * Different flight modes
 */
object SensesoarMode extends Enumeration {
  val _UNKNOWN = Value(0)
  /**
   * Gliding mode with motors off
   */
  val GLIDING = Value(1)
  /**
   * Autonomous flight
   */
  val AUTONOMOUS = Value(2)
  /**
   * RC controlled
   */
  val MANUAL = Value(3)
}
