// Code generated by sbt-mavgen. Manual edits will be overwritten
package scavlink.message.enums

/**
 * SERIAL_CONTROL flags (bitmask)
 */
object SerialControlFlag extends Enumeration with Flag {
  val _UNKNOWN = Value(0)
  /**
   * Set if this is a reply
   */
  val REPLY = Value(1)
  /**
   * Set if the sender wants the receiver to send a response as another SERIAL_CONTROL message
   */
  val RESPOND = Value(2)
  /**
   * Set if access to the serial port should be removed from whatever driver is currently using it, giving exclusive access to the SERIAL_CONTROL protocol. The port can be handed back by sending a request without this flag set
   */
  val EXCLUSIVE = Value(4)
  /**
   * Block on writes to the serial port
   */
  val BLOCKING = Value(8)
  /**
   * Send multiple replies until port is drained
   */
  val MULTI = Value(16)
}
