// Code generated by sbt-mavgen. Manual edits will be overwritten
package scavlink.message.enums

/**
 * SERIAL_CONTROL device types
 */
object SerialControlDev extends Enumeration {
  /**
   * First telemetry port
   */
  val TELEM1 = Value(0)
  /**
   * Second telemetry port
   */
  val TELEM2 = Value(1)
  /**
   * First GPS port
   */
  val GPS1 = Value(2)
  /**
   * Second GPS port
   */
  val GPS2 = Value(3)
}
