// Code generated by sbt-mavgen. Manual edits will be overwritten
package scavlink.message.enums

/**
 * Slugs-specific navigation modes.
 */
object SlugsMode extends Enumeration {
  /**
   * No change to SLUGS mode.
   */
  val NONE = Value(0)
  /**
   * Vehicle is in liftoff mode.
   */
  val LIFTOFF = Value(1)
  /**
   * Vehicle is in passthrough mode, being controlled by a pilot.
   */
  val PASSTHROUGH = Value(2)
  /**
   * Vehicle is in waypoint mode, navigating to waypoints.
   */
  val WAYPOINT = Value(3)
  /**
   * Vehicle is executing mid-level commands.
   */
  val MID_LEVEL = Value(4)
  /**
   * Vehicle is returning to the home location.
   */
  val RETURNING = Value(5)
  /**
   * Vehicle is landing.
   */
  val LANDING = Value(6)
  /**
   * Lost connection with vehicle.
   */
  val LOST = Value(7)
  /**
   * Vehicle is in selective passthrough mode, where selected surfaces are being manually controlled.
   */
  val SELECTIVE_PASSTHROUGH = Value(8)
  /**
   * Vehicle is in ISR mode, performing reconaissance at a point specified by ISR_LOCATION message.
   */
  val ISR = Value(9)
  /**
   * Vehicle is patrolling along lines between waypoints.
   */
  val LINE_PATROL = Value(10)
  /**
   * Vehicle is grounded or an error has occurred.
   */
  val GROUNDED = Value(11)
}
