// Code generated by sbt-mavgen. Manual edits will be overwritten
package scavlink.message.enums

/**
 * Mode currently commanded by pilot
 */
object UalbertaPilotMode extends Enumeration {
  val _UNKNOWN = Value(0)
  /**
   * sdf
   */
  val MANUAL = Value(1)
  /**
   * dfs
   */
  val AUTO = Value(2)
  /**
   * Rotomotion mode
   */
  val ROTO = Value(3)
}
