// Code generated by sbt-mavgen. Manual edits will be overwritten
package scavlink.message.enums

/**
 * Available autopilot modes for ualberta uav
 */
object UalbertaAutopilotMode extends Enumeration {
  val _UNKNOWN = Value(0)
  /**
   * Raw input pulse widts sent to output
   */
  val MANUAL_DIRECT = Value(1)
  /**
   * Inputs are normalized using calibration, the converted back to raw pulse widths for output
   */
  val MANUAL_SCALED = Value(2)
  /**
   * dfsdfs
   */
  val AUTO_PID_ATT = Value(3)
  /**
   * dfsfds
   */
  val AUTO_PID_VEL = Value(4)
  /**
   * dfsdfsdfs
   */
  val AUTO_PID_POS = Value(5)
}
