// Code generated by sbt-mavgen. Manual edits will be overwritten
package scavlink.message.enums

/**
 * Navigation filter mode
 */
object UalbertaNavMode extends Enumeration {
  val _UNKNOWN = Value(0)
  val AHRS_INIT = Value(1)
  /**
   * AHRS mode
   */
  val AHRS = Value(2)
  /**
   * INS/GPS initialization mode
   */
  val INS_GPS_INIT = Value(3)
  /**
   * INS/GPS mode
   */
  val INS_GPS = Value(4)
}
