// Code generated by sbt-mavgen. Manual edits will be overwritten
package scavlink.connection.marshal

import scavlink.message.{Message, Bundle}
import scavlink.message.ASLUAV._
import scavlink.message.enums._
import akka.util.{ByteIterator, ByteStringBuilder}

object ASLUAVMarshaller extends BundleMarshaller {
  val bundle = Bundle.ASLUAV

  def magic = Map(201 -> 218, 202 -> 231, 203 -> 0, 204 -> 251, 205 -> 97)

  def _marshal(message: Message)(implicit builder: ByteStringBuilder) = message match {
    case SensPower(a,b,c,d) => _float(a); _float(b); _float(c); _float(d)
    case SensMppt(a,b,c,d,e,f,g,h,i,j,k,l,m) => _uint64_t(a); _float(b); _float(c); _float(f); _float(g); _float(j); _float(k); _uint16_t(d); _uint16_t(h); _uint16_t(l); _uint8_t(e); _uint8_t(i); _uint8_t(m)
    case AslctrlData(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y) => _uint64_t(a); _float(c); _float(d); _float(e); _float(f); _float(g); _float(h); _float(i); _float(j); _float(k); _float(l); _float(m); _float(n); _float(p); _float(q); _float(r); _float(s); _float(t); _float(u); _float(v); _float(w); _float(x); _float(y); _uint8_t(b); _uint8_t(o)
    case AslctrlDebug(a,b,c,d,e,f,g,h,i,j,k) => _uint32_t(a); _float(d); _float(e); _float(f); _float(g); _float(h); _float(i); _float(j); _float(k); _uint8_t(b); _uint8_t(c)
    case AsluavStatus(a,b,c,d) => _float(d); _uint8_t(a); _uint8_t(b); _uint8_t_(8)(c)
  }

  def _unmarshal(msgId: Int)(implicit iter: ByteIterator) = msgId match {
    case 201 => SensPower(adc121VspbVolt=float, adc121CspbAmp=float, adc121Cs1Amp=float, adc121Cs2Amp=float)
    case 202 => SensMppt(mpptTimestamp=uint64_t, mppt1Volt=float, mppt1Amp=float, mppt2Volt=float, mppt2Amp=float, mppt3Volt=float, mppt3Amp=float, mppt1Pwm=uint16_t, mppt2Pwm=uint16_t, mppt3Pwm=uint16_t, mppt1Status=uint8_t, mppt2Status=uint8_t, mppt3Status=uint8_t)
    case 203 => AslctrlData(timestamp=uint64_t, h=float, hRef=float, hRefT=float, pitchangle=float, pitchangleref=float, q=float, qRef=float, uElev=float, uThrot=float, uThrot2=float, aZ=float, airspeedref=float, yawangle=float, yawangleref=float, rollangle=float, rollangleref=float, p=float, pRef=float, r=float, rRef=float, uAil=float, uRud=float, aslctrlMode=uint8_t, spoilersengaged=uint8_t)
    case 204 => AslctrlDebug(i321=uint32_t, f1=float, f2=float, f3=float, f4=float, f5=float, f6=float, f7=float, f8=float, i81=uint8_t, i82=uint8_t)
    case 205 => AsluavStatus(motorRpm=float, ledStatus=uint8_t, satcomStatus=uint8_t, servoStatus=uint8_t_(8))
  }
}
